name: Clean

on:
  pull_request:
    types: [closed]


jobs:
  detect:
    defaults:
      run:
        shell: bash
    runs-on:
      - ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEEN_GITHUB_PAT }}